name: Deploy Astro Project

on:
  push:
    branches:
      - master
      - dev

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
        id: build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: astro-build
          path: ./dist

      - name: Set target branch
        id: set-target-branch
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
            echo "TARGET_BRANCH=master" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            echo "TARGET_BRANCH=som-summarize" >> $GITHUB_ENV
          fi

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: Sinoptik93/site-frontend
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ env.TARGET_BRANCH }}

      - name: Copy build to target repository
        run: |
          cp -r ./dist/* ./public

      - name: Setup GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "${{ secrets.GPG_KEYGRIP }}" | gpg --batch --import-ownertrust
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEYGRIP: ${{ secrets.GPG_KEYGRIP }}

      - name: Configure Git for GPG signing
        run: |
          git config --global user.signingkey ${{ secrets.GPG_KEY_ID }}
          git config --global commit.gpgSign true
          git config --global user.name 'Sergey Chepukhin'
          git config --global user.email 'chepukhin.sergey@gmail.com'

      - name: Commit and push changes
        run: |
          git add .
          git commit -S -m "update dodo kids landing"
          git push origin ${{ env.TARGET_BRANCH }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: dodo kids landing update
          branch: deployment-branch
          base: ${{ env.TARGET_BRANCH }}
          title: 'Dodo kids landing'

      - name: Add comment to pull request
        uses: actions/github-script@v7
        id: comment-script
        with:
          script: |
            const script = require('./githubPRCommentScript.js')
            await script({github, context, core})
